"""Email channel adapter — SMTP, multipart, per-recipient (NEVER BCC).

Per US0019 + TC0214: This adapter sends ONE email per recipient via the
same SMTP connection. NEVER uses BCC — leaking other recipients' addresses
in the To/Cc/Bcc headers would be a privacy violation.

Plain-text fallback: derived from the markdown body via strip_markdown(),
not regenerated by an LLM.
"""

from __future__ import annotations

import contextlib
import logging
import os
import smtplib
from collections.abc import Callable
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from tenacity import (
    RetryError,
    retry,
    retry_if_exception_type,
    stop_after_attempt,
    wait_exponential,
)

from techletter.compose.issue import RenderedIssue
from techletter.delivery.base import (
    ChannelSendError,
    Recipient,
    SendReport,
)
from techletter.delivery.escaping import strip_markdown

__all__ = ["EmailAdapter", "SmtpFactory"]

logger = logging.getLogger(__name__)

SmtpFactory = Callable[[], smtplib.SMTP]


def _default_smtp_factory() -> smtplib.SMTP:
    """Default factory: builds an SMTP connection from environment variables.

    Required env vars: SMTP_HOST, SMTP_USER, SMTP_PASS, SMTP_FROM.
    Optional: SMTP_PORT (default 587).
    """
    host = os.environ.get("SMTP_HOST")
    port = int(os.environ.get("SMTP_PORT", "587"))
    user = os.environ.get("SMTP_USER")
    password = os.environ.get("SMTP_PASS")
    if not (host and user and password):
        raise ChannelSendError("email: SMTP_HOST/SMTP_USER/SMTP_PASS must be set in environment")
    smtp = smtplib.SMTP(host, port)
    smtp.starttls()
    smtp.login(user, password)
    return smtp


class EmailAdapter:
    """ChannelAdapter implementation for SMTP email.

    Critical privacy invariant (TC0214):
    - One MIMEMultipart per recipient
    - To: header is the SINGLE recipient
    - NEVER uses BCC (would leak addresses to all recipients)
    - One SMTP connection per send pass (efficiency)
    """

    name: str = "email"

    def __init__(
        self,
        *,
        smtp_factory: SmtpFactory | None = None,
        from_addr: str | None = None,
    ) -> None:
        self._smtp_factory: SmtpFactory = smtp_factory or _default_smtp_factory
        self._from_addr = from_addr or os.environ.get("SMTP_FROM")

    def send(self, issue: RenderedIssue, recipients: list[Recipient]) -> SendReport:
        if not recipients:
            return SendReport(
                channel=self.name,
                status="ok",
                recipient_count=0,
                success_count=0,
                failure_count=0,
                errors=[],
            )

        if not self._from_addr:
            return SendReport(
                channel=self.name,
                status="failed",
                recipient_count=len(recipients),
                success_count=0,
                failure_count=len(recipients),
                errors=["email: SMTP_FROM not configured"],
            )

        try:
            smtp = self._open_smtp_with_retry()
        except RetryError as e:
            inner = e.last_attempt.exception()
            return SendReport(
                channel=self.name,
                status="failed",
                recipient_count=len(recipients),
                success_count=0,
                failure_count=len(recipients),
                errors=[f"email: SMTP connect failed after retries: {inner}"],
            )

        success_count = 0
        failure_count = 0
        errors: list[str] = []

        try:
            subject = f"Tech-Letter — {issue.issue_id}"
            plain_body = strip_markdown(issue.body_md)
            html_body = self._wrap_html(issue.body_md)

            for r in recipients:
                try:
                    msg = self._build_message(
                        subject=subject,
                        to_addr=r.address,
                        plain=plain_body,
                        html=html_body,
                    )
                    # TC0214: smtp.send_message uses To header only — never BCC
                    smtp.send_message(msg)
                    success_count += 1
                except Exception as e:
                    logger.warning("email: failed to send to %s: %s", r.address, e)
                    failure_count += 1
                    errors.append(f"{r.address}: {e}")
        finally:
            with contextlib.suppress(Exception):
                smtp.quit()

        status = self._derive_status(success_count, failure_count, len(recipients))
        return SendReport(
            channel=self.name,
            status=status,
            recipient_count=len(recipients),
            success_count=success_count,
            failure_count=failure_count,
            errors=errors,
        )

    @retry(
        stop=stop_after_attempt(5),
        wait=wait_exponential(multiplier=0, min=0, max=0),  # no wait in tests
        retry=retry_if_exception_type((smtplib.SMTPConnectError, ConnectionError, TimeoutError)),
        reraise=False,
    )
    def _open_smtp_with_retry(self) -> smtplib.SMTP:
        return self._smtp_factory()

    def _build_message(self, *, subject: str, to_addr: str, plain: str, html: str) -> MIMEMultipart:
        """Build a multipart/alternative message for ONE recipient.

        Privacy invariant: To: header contains exactly ONE address.
        No Cc: or Bcc: headers are ever set.
        """
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = self._from_addr or ""
        msg["To"] = to_addr  # SINGLE recipient — TC0214
        # Explicitly do NOT set Cc or Bcc.
        msg.attach(MIMEText(plain, "plain", "utf-8"))
        msg.attach(MIMEText(html, "html", "utf-8"))
        return msg

    @staticmethod
    def _wrap_html(body_md: str) -> str:
        """Minimal HTML wrapper around the markdown body.

        We escape the body for safety (no template engine needed for v1).
        """
        body_escaped = body_md.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        return (
            "<!DOCTYPE html><html><head><meta charset='utf-8'></head>"
            "<body><pre style='font-family: monospace; white-space: pre-wrap;'>"
            f"{body_escaped}"
            "</pre></body></html>"
        )

    @staticmethod
    def _derive_status(success: int, failure: int, total: int) -> str:
        if failure == 0:
            return "ok"
        if success == 0:
            return "failed"
        return "partial"
